---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: netbox
  labels:
    name: nginx
    component: frontend
    part-of: netbox
spec:
  selector:
    matchLabels:
      name: nginx
      component: frontend
      part-of: netbox
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
        component: frontend
        part-of: netbox
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          command: ["nginx"]
          args: ["-c", "/etc/netbox-nginx/nginx.conf","-g", "daemon off;"]
          volumeMounts:
            - name: netbox-static-files
              mountPath: /opt/netbox/netbox/static
            - name: netbox-nginx-config
              mountPath: /etc/netbox-nginx
      restartPolicy: Always
      volumes:
        - name: netbox-static-files
          persistentVolumeClaim:
            claimName: netbox-static-files
        - name: netbox-nginx-config
          configMap:
            name: shared-nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: netbox
  labels:
    name: nginx
    component: frontend
    part-of: netbox
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: nginx
    component: frontend
    part-of: netbox
