---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: netbox
  labels:
    name: postgres
    component: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
        component: database
    spec:
      containers:
      - image: postgres:10-alpine
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-env
        volumeMounts:
        - name: netbox-pg-backups
          mountPath: /var/lib/backups
      volumes:
      - name: netbox-pg-backups
        persistentVolumeClaim:
         claimName: netbox-pg-backups
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: netbox
  labels:
    name: postgres
    component: database
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 5432
    targetPort: 5432
  selector:
    name: postgres
    component: database

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  namespace: netbox
data:
  POSTGRES_DB: netbox
  POSTGRES_USER: netbox
  POSTGRES_PASSWORD: J5brHrAXFLQSif0K


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-pg-backups
  namespace: netbox
  labels:
    pvcname: netbox-pg-backups
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
