---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: netbox
  labels:
    name: postgres
    component: database
    part-of: netbox
spec:
  selector:
    matchLabels:
      name: postgres
      component: database
      part-of: netbox
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
        component: database
        part-of: netbox
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shared-database-variables
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: shared-database-variables
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-database-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: netbox-pg-backups
              mountPath: /var/lib/backups
      volumes:
        - name: netbox-pg-backups
          persistentVolumeClaim:
           claimName: netbox-pg-backups
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: netbox
  labels:
    name: postgres
    component: database
    part-of: netbox
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 5432
      targetPort: 5432
  selector:
    name: postgres
    component: database
    part-of: netbox

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-pg-backups
  namespace: netbox
  labels:
    pvcname: netbox-pg-backups
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
